.PHONY: install dev deploy destroy outputs

STACK_NAME = fastapi-cdk-starter

# Install all dependencies
install:
	npm install
	uv sync

# Run FastAPI locally on :8000 (auto-loads .env if present)
dev:
	env $$(cat .env 2>/dev/null | grep -v '^\#' | xargs) uv run uvicorn app.main:app --reload --port 8000

# Deploy CDK stack
deploy:
	npx cdk deploy --require-approval never

# Tear down all AWS resources
destroy:
	npx cdk destroy

# Print stack outputs and write .env for local dev
# DATABASE_URL must be set manually in .env (local PostgreSQL or Neon)
outputs:
	@aws cloudformation describe-stacks \
		--stack-name $(STACK_NAME) \
		--query "Stacks[0].Outputs" \
		--output table
	@echo "# Generated by 'make outputs' — do not commit" > .env
	@echo "# DATABASE_URL=xxxxxxxx" >> .env
	@aws cloudformation describe-stacks \
		--stack-name $(STACK_NAME) \
		--query "Stacks[0].Outputs[*].[OutputKey,OutputValue]" \
		--output text | while read key value; do \
			case $$key in \
				ApiUrl)           echo "API_URL=$$value"             >> .env ;; \
				UserPoolId)       echo "USER_POOL_ID=$$value"        >> .env ;; \
				UserPoolClientId) echo "USER_POOL_CLIENT_ID=$$value" >> .env ;; \
				Region)           echo "AWS_REGION=$$value"          >> .env ;; \
			esac \
		done
	@echo ".env written:" && cat .env
