.PHONY: install dev deploy destroy outputs env

STACK_NAME = fastapi-cdk-starter

# Install all dependencies
install:
	npm install
	uv sync

# Run FastAPI locally on :8000 (auto-loads .env if present)
dev:
	env $$(cat .env 2>/dev/null | grep -v '^\#' | xargs) uv run uvicorn app.main:app --reload --port 8000

# Deploy CDK stack
deploy:
	npx cdk deploy --require-approval never

# Tear down all AWS resources
destroy:
	npx cdk destroy

# Print stack outputs (copy these into your frontend env vars)
outputs:
	aws cloudformation describe-stacks \
		--stack-name $(STACK_NAME) \
		--query "Stacks[0].Outputs" \
		--output table

# Write .env from CloudFormation outputs + DynamoDB table names
env:
	@echo "# Generated by 'make env' — do not commit" > .env
	@aws cloudformation describe-stacks \
		--stack-name $(STACK_NAME) \
		--query "Stacks[0].Outputs[*].[OutputKey,OutputValue]" \
		--output text | while read key value; do \
			case $$key in \
				ApiUrl)           echo "API_URL=$$value"            >> .env ;; \
				UserPoolId)       echo "USER_POOL_ID=$$value"       >> .env ;; \
				UserPoolClientId) echo "USER_POOL_CLIENT_ID=$$value" >> .env ;; \
				Region)           echo "AWS_REGION=$$value"         >> .env ;; \
			esac \
		done
	@aws dynamodb list-tables --output text --query "TableNames[]" | tr '\t' '\n' | \
		grep "^$(STACK_NAME)-" | while read table; do \
			suffix=$$(echo $$table | sed 's/^$(STACK_NAME)-//'); \
			varname=$$(echo $$suffix | tr 'a-z-' 'A-Z_')_TABLE; \
			echo "$$varname=$$table" >> .env; \
		done
	@echo ".env written:" && cat .env
