#!/usr/bin/env bash
# Reads CloudFormation outputs and writes frontend/.env.local.
# Works with any CloudFormation stack (SAM or CDK — outputs are identical).
# Usage: ./scripts/post-deploy.sh [stack-name] [region]
set -euo pipefail

STACK_NAME="${1:-nextjs-fastapi-template}"
REGION="${2:-us-east-1}"
ENV_FILE="frontend/.env.local"

echo "→ Fetching outputs for stack: $STACK_NAME ($REGION)"

get_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

USER_POOL_ID=$(get_output "UserPoolId")
USER_POOL_CLIENT_ID=$(get_output "UserPoolClientId")
API_URL=$(get_output "ApiUrl")
REGION_OUT=$(get_output "Region")

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/post-deploy.sh — do not commit
NEXT_PUBLIC_AWS_REGION=$REGION_OUT
NEXT_PUBLIC_USER_POOL_ID=$USER_POOL_ID
NEXT_PUBLIC_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
NEXT_PUBLIC_API_URL=$API_URL
EOF

echo ""
echo "✓ Written to $ENV_FILE"
echo ""
echo "  User Pool ID :    $USER_POOL_ID"
echo "  App Client ID:    $USER_POOL_CLIENT_ID"
echo "  API URL       :   $API_URL"
echo ""
echo "Next steps:"
echo "  1. cd frontend && npm run dev   (local test with real AWS backend)"
echo "  2. Set the same 4 vars in Amplify Console → App settings → Environment variables"
echo "  3. Connect your repo to Amplify Hosting and deploy"
